symfonycasts_reset_password:
    # point at your generated repository
    request_password_repository: App\Repository\ResetPasswordRequestRepository

    # how long (in seconds) a token is valid for
    lifetime: 3600

    # how long before the same user can request again
    throttle_limit: 0

    # whether to auto-clean up expired rows
    enable_garbage_collection: true
